export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENT_FAILED = "FETCH_INGREDIENT_FAILED";

export const SEND_ORDER_SUCCESS = "SEND_ORDER_SUCCESS";
export const SEND_ORDER_FAILED = "SEND_ORDER_FAILED";
export const SEND_ORDER_LOADING = "SEND_ORDER_LOADING";
export const SEND_ORDER_INIT = "SEND_ORDER_INIT";

export const FETCH_ORDERS_INIT = "FETCH_ORDERS_INIT";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const SET_BURGER_BUILD_STATUS = "SET_BURGER_BUILD_STATUS";
export const SET_REDIRECT_PATH = "SET_REDIRECT_PATH";
